apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: sspyataev/web-server:latest
          readinessProbe:
            httpGet:
              path: /index.html 
              port: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
          imagePullPolicy: Always
          volumeMounts:
          - name: app
            mountPath: /app
      initContainers:
        - name: init-index
          image: busybox:1.31.0
          imagePullPolicy: Always
          volumeMounts:
          - name: app
            mountPath: /app
          command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumes:
      - name: app
        emptyDir: {}
        