apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "shop.104.154.39.165.nip.io"
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: {{ .Values.service.port }}