apiVersion: v1
kind: Pod
metadata:
  name: web-server
  labels:
    server: web

spec:
  containers:
    - name: web-server
      image: sspyataev/web-server:latest
      volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
    - name: init-index
      image: busybox:1.31.0
      volumeMounts:
      - name: app
        mountPath: /app
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
  volumes:
  - name: app
    emptyDir: {}